sudo: required
language: ruby

services:
  - docker

script:
  - npm install
  - npm test
  - npm run coveralls
  - docker build -t classpip/classpip-services .

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
